name: Bazel Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  bazel-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout mlir-tutorial
      uses: actions/checkout@v4

    - name: Validate LLVM Commit
      run: |
        ./build_tools/github_actions/lint_llvm_commit.sh .

    - name: Get LLVM Version
      id: llvm-version
      shell: bash
      run: |
        echo "version=$(cat ${{ github.workspace }}/build_tools/llvm_version.txt)" >> $GITHUB_OUTPUT

    - name: Setup Bazelisk
      uses: bazelbuild/setup-bazelisk@v2

    - name: Mount Bazel Cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: ${{ runner.os }}-mlir_tutorial__bazelbuild-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE') }}
        restore-keys: |
          ${{ runner.os }}-mlir_tutorial__bazelbuild-

    - name: Build mlir tutorial
      shell: bash
      run: |
        ./build_tools/github_actions/ci_build_bazel.sh
